version: "3.6"
services: 
  db: 
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
    image: mysql:5.7
    restart: always
    volumes: 
      - "./mysql:/var/lib/mysql"

  wordpress: 
    environment: 
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress  
    image: wordpress:latest
    ports: 
      - "8000:80"
    volumes:      
      - "./wp:/var/www/html" 

